# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-18 10:02
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Login',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=5, primary_key=True, serialize=False)),
                ('address', models.URLField(verbose_name='URL')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='接口名称')),
                ('method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('files', models.FileField(default='无', null=True, storage=django.core.files.storage.FileSystemStorage(location='/case'), upload_to='', verbose_name='测试文件-Excel')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
            },
        ),
    ]
