# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apis',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=20, verbose_name='URL')),
                ('name', models.CharField(max_length=20, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('files', models.FileField(default='无', upload_to='./case', verbose_name='测试文件-Excel')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
            },
        ),
        migrations.DeleteModel(
            name='Api_Login',
        ),
    ]
