# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170920_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_login',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=20)),
                ('api_address', models.URLField(max_length=50, verbose_name='接口地址')),
                ('params_login_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('params_login_password', models.CharField(max_length=10, verbose_name='密码')),
                ('params_terminal_type', models.CharField(max_length=10, verbose_name='终端类型')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('apis_foreignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.apis')),
            ],
            options={
                'verbose_name': '登录接口',
                'verbose_name_plural': '登录接口',
            },
        ),
    ]
