# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_api_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='address',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
    ]
