# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20170920_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_login',
            name='apis_foreignKey',
        ),
        migrations.AlterField(
            model_name='api_login',
            name='api_name',
            field=models.CharField(max_length=20, verbose_name='接口名称'),
        ),
    ]
