# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20170920_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '接口详情',
                'verbose_name_plural': '接口详情',
            },
        ),
    ]
