# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api',
        ),
        migrations.DeleteModel(
            name='api_login',
        ),
        migrations.AddField(
            model_name='apis',
            name='params',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
